[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "polygraphs"
version = "0.0.22a1"
authors = [
    {name="Alexandros Koliousis", email="ak@akoliousis.com"},
    {name="Amil Mohanan", email="amil@mohanan.net"}
]
license = "MIT"
description = "Philosophical simulations on networks"
readme = "README.md"
keywords = ["philosophy", "epistemology", "simulation"]
requires-python = ">=3.12"
dependencies = [
    "PyYAML",
    "pandas",
    "numpy",
    "h5py",
    "matplotlib",
    "networkx",
    "torch",
    "ptgraph @ git+https://github.com/polygraphs/ptgraph.git@main",
]

[project.urls]
Repository = "https://github.com/alexandroskoliousis/polygraphs"
Documentation = "https://akoliousis.com/polygraphs/"

[project.scripts]
polygraphs = "polygraphs.run:run"

[tool.setuptools.packages.find]
include = ["polygraphs*"]
